"frm1601EQ:txtYear" = "fields.frm1601EQ:txtYear"
"frm1601EQ:optQuarter:1" = "fields.frm1601EQ:optQuarter:1"
"frm1601EQ:optQuarter:2" = "fields.frm1601EQ:optQuarter:2"
"frm1601EQ:optQuarter:3" = "fields.frm1601EQ:optQuarter:3"
"frm1601EQ:optQuarter:4" = "fields.frm1601EQ:optQuarter:4"
"frm1601EQ:optAmend:Y" = "fields.frm1601EQ:optAmend:Y"
"frm1601EQ:optAmend:N" = "fields.frm1601EQ:optAmend:N"
"frm1601EQ:optWithheld:Y" = "fields.frm1601EQ:optWithheld:Y"
"frm1601EQ:optWithheld:N" = "fields.frm1601EQ:optWithheld:N"
"frm1601EQ:txtNoSheets" = "fields.frm1601EQ:txtNoSheets"
"frm1601EQ:txtTIN1" = "fields.frm1601EQ:txtTIN1"
"frm1601EQ:txtTIN2" = "fields.frm1601EQ:txtTIN2"
"frm1601EQ:txtTIN3" = "fields.frm1601EQ:txtTIN3"
"frm1601EQ:txtBranchCode" = "fields.frm1601EQ:txtBranchCode"
"frm1601EQ:txtRDOCode" = "fields.frm1601EQ:txtRDOCode"
"frm1601EQ:txtTaxpayerName" = "fields.frm1601EQ:txtTaxpayerName"
"frm1601EQ:txtLineBus" = "fields.frm1601EQ:txtLineBus"
"frm1601EQ:txtAddress" = "fields.frm1601EQ:txtAddress"
"frm1601EQ:txtZipCode" = "fields.frm1601EQ:txtZipCode"
"frm1601EQ:txtTelNum" = "fields.frm1601EQ:txtTelNum"
"frm1601EQ:optCategory:P" = "fields.frm1601EQ:optCategory:P"
"frm1601EQ:optCategory:G" = "fields.frm1601EQ:optCategory:G"
"txtEmail" = "fields.txtEmail"
"frm1601EQ:txtAtcCd1" = "fields.frm1601EQ:txtAtcCd1"
"frm1601EQ:txtTaxBase1" = "fields.frm1601EQ:txtTaxBase1"
"frm1601EQ:txtTaxRate1" = "fields.frm1601EQ:txtTaxRate1"
"frm1601EQ:txtTaxbeWithHeld1" = "fields.frm1601EQ:txtTaxbeWithHeld1"
"frm1601EQ:txtAtcCd2" = "fields.frm1601EQ:txtAtcCd2"
"frm1601EQ:txtTaxBase2" = "fields.frm1601EQ:txtTaxBase2"
"frm1601EQ:txtTaxRate2" = "fields.frm1601EQ:txtTaxRate2"
"frm1601EQ:txtTaxbeWithHeld2" = "fields.frm1601EQ:txtTaxbeWithHeld2"
"frm1601EQ:txtAtcCd3" = "fields.frm1601EQ:txtAtcCd3"
"frm1601EQ:txtTaxBase3" = "fields.frm1601EQ:txtTaxBase3"
"frm1601EQ:txtTaxRate3" = "fields.frm1601EQ:txtTaxRate3"
"frm1601EQ:txtTaxbeWithHeld3" = "fields.frm1601EQ:txtTaxbeWithHeld3"
"frm1601EQ:txtAtcCd4" = "fields.frm1601EQ:txtAtcCd4"
"frm1601EQ:txtTaxBase4" = "fields.frm1601EQ:txtTaxBase4"
"frm1601EQ:txtTaxRate4" = "fields.frm1601EQ:txtTaxRate4"
"frm1601EQ:txtTaxbeWithHeld4" = "fields.frm1601EQ:txtTaxbeWithHeld4"
"frm1601EQ:txtAtcCd5" = "fields.frm1601EQ:txtAtcCd5"
"frm1601EQ:txtTaxBase5" = "fields.frm1601EQ:txtTaxBase5"
"frm1601EQ:txtTaxRate5" = "fields.frm1601EQ:txtTaxRate5"
"frm1601EQ:txtTaxbeWithHeld5" = "fields.frm1601EQ:txtTaxbeWithHeld5"
"frm1601EQ:txtAtcCd6" = "fields.frm1601EQ:txtAtcCd6"
"frm1601EQ:txtTaxBase6" = "fields.frm1601EQ:txtTaxBase6"
"frm1601EQ:txtTaxRate6" = "fields.frm1601EQ:txtTaxRate6"
"frm1601EQ:txtTaxbeWithHeld6" = "fields.frm1601EQ:txtTaxbeWithHeld6"
"frm1601EQ:txtTotalOtherTax" = "fields.frm1601EQ:txtTotalOtherTax"
"frm1601EQ:txtTax19" = "fields.frm1601EQ:txtTax19"
"frm1601EQ:txtTax20" = "fields.frm1601EQ:txtTax20"
"frm1601EQ:txtTax21" = "fields.frm1601EQ:txtTax21"
"frm1601EQ:txtTax22" = "fields.frm1601EQ:txtTax22"
"frm1601EQ:txtTax23" = "fields.frm1601EQ:txtTax23"
"frm1601EQ:txtTax24" = "fields.frm1601EQ:txtTax24"
"frm1601EQ:txtTax25" = "fields.frm1601EQ:txtTax25"
"frm1601EQ:txtTax26" = "fields.frm1601EQ:txtTax26"
"frm1601EQ:txtTax27" = "fields.frm1601EQ:txtTax27"
"frm1601EQ:txtTax28" = "fields.frm1601EQ:txtTax28"
"frm1601EQ:txtTax29" = "fields.frm1601EQ:txtTax29"
"frm1601EQ:txtTax30" = "fields.frm1601EQ:txtTax30"
"frm1601EQ:ifRefund" = "fields.frm1601EQ:ifRefund"
"frm1601EQ:ifIssueCert" = "fields.frm1601EQ:ifIssueCert"
"frm1601EQ:ifCarriedOver" = "fields.frm1601EQ:ifCarriedOver"
"txtTaxAgentNo" = "fields.txtTaxAgentNo"
"txtDateIssue" = "fields.txtDateIssue"
"txtDateExpiry" = "fields.txtDateExpiry"
"frm1601EQ:txtAgency33" = "fields.frm1601EQ:txtAgency33"
"frm1601EQ:txtNumber33" = "fields.frm1601EQ:txtNumber33"
"frm1601EQ:txtDate33" = "fields.frm1601EQ:txtDate33"
"frm1601EQ:txtAmount33" = "fields.frm1601EQ:txtAmount33"
"frm1601EQ:txtAgency34" = "fields.frm1601EQ:txtAgency34"
"frm1601EQ:txtNumber34" = "fields.frm1601EQ:txtNumber34"
"frm1601EQ:txtDate34" = "fields.frm1601EQ:txtDate34"
"frm1601EQ:txtAmount34" = "fields.frm1601EQ:txtAmount34"
"frm1601EQ:txtAgency35" = "fields.frm1601EQ:txtAgency35"
"frm1601EQ:txtNumber35" = "fields.frm1601EQ:txtNumber35"
"frm1601EQ:txtDate35" = "fields.frm1601EQ:txtDate35"
"frm1601EQ:txtAmount35" = "fields.frm1601EQ:txtAmount35"
"frm1601EQ:txtParticular36" = "fields.frm1601EQ:txtParticular36"
"frm1601EQ:txtAgency36" = "fields.frm1601EQ:txtAgency36"
"frm1601EQ:txtNumber36" = "fields.frm1601EQ:txtNumber36"
"frm1601EQ:txtDate36" = "fields.frm1601EQ:txtDate36"
"frm1601EQ:txtAmount36" = "fields.frm1601EQ:txtAmount36"
"AtcCode1" = "fields.AtcCode1"
"AtcCode2" = "fields.AtcCode2"
"AtcCode3" = "fields.AtcCode3"
"AtcCode4" = "fields.AtcCode4"
"AtcCode5" = "fields.AtcCode5"
"AtcCode6" = "fields.AtcCode6"
"AtcCode7" = "fields.AtcCode7"
"AtcCode8" = "fields.AtcCode8"
"AtcCode9" = "fields.AtcCode9"
"AtcCode10" = "fields.AtcCode10"
"AtcCode11" = "fields.AtcCode11"
"AtcCode12" = "fields.AtcCode12"
"AtcCode13" = "fields.AtcCode13"
"AtcCode14" = "fields.AtcCode14"
"AtcCode15" = "fields.AtcCode15"
"AtcCode16" = "fields.AtcCode16"
"AtcCode17" = "fields.AtcCode17"
"AtcCode18" = "fields.AtcCode18"
"AtcCode19" = "fields.AtcCode19"
"AtcCode20" = "fields.AtcCode20"
"AtcCode21" = "fields.AtcCode21"
"AtcCode22" = "fields.AtcCode22"
"AtcCode23" = "fields.AtcCode23"
"AtcCode24" = "fields.AtcCode24"
"AtcCode25" = "fields.AtcCode25"
"AtcCode26" = "fields.AtcCode26"
"AtcCode27" = "fields.AtcCode27"
"AtcCode28" = "fields.AtcCode28"
"AtcCode29" = "fields.AtcCode29"
"AtcCode30" = "fields.AtcCode30"
"AtcCode31" = "fields.AtcCode31"
"AtcCode32" = "fields.AtcCode32"
"AtcCode33" = "fields.AtcCode33"
"AtcCode34" = "fields.AtcCode34"
"AtcCode35" = "fields.AtcCode35"
"AtcCode36" = "fields.AtcCode36"
"AtcCode37" = "fields.AtcCode37"
"AtcCode38" = "fields.AtcCode38"
"AtcCode39" = "fields.AtcCode39"
"AtcCode40" = "fields.AtcCode40"
"AtcCode41" = "fields.AtcCode41"
"AtcCode42" = "fields.AtcCode42"
"AtcCode43" = "fields.AtcCode43"
"AtcCode44" = "fields.AtcCode44"
"AtcCode45" = "fields.AtcCode45"
"AtcCode46" = "fields.AtcCode46"
"AtcCode47" = "fields.AtcCode47"
"AtcCode48" = "fields.AtcCode48"
"AtcCode49" = "fields.AtcCode49"
"AtcCode50" = "fields.AtcCode50"
"AtcCode51" = "fields.AtcCode51"
"AtcCode52" = "fields.AtcCode52"
"AtcCode53" = "fields.AtcCode53"
"AtcCode54" = "fields.AtcCode54"
"AtcCode55" = "fields.AtcCode55"
"AtcCode56" = "fields.AtcCode56"
"AtcCode57" = "fields.AtcCode57"
"AtcCode58" = "fields.AtcCode58"
"AtcCode59" = "fields.AtcCode59"
"AtcCode60" = "fields.AtcCode60"
"AtcCode61" = "fields.AtcCode61"
"AtcCode62" = "fields.AtcCode62"
"AtcCode63" = "fields.AtcCode63"
"AtcCode64" = "fields.AtcCode64"
"AtcCode65" = "fields.AtcCode65"
"AtcCode66" = "fields.AtcCode66"
"AtcCode67" = "fields.AtcCode67"
"AtcCode68" = "fields.AtcCode68"
"AtcCode69" = "fields.AtcCode69"
"AtcCode70" = "fields.AtcCode70"
"AtcCode71" = "fields.AtcCode71"
"AtcCode72" = "fields.AtcCode72"
"AtcCode73" = "fields.AtcCode73"
"AtcCode74" = "fields.AtcCode74"
"AtcCode75" = "fields.AtcCode75"
"AtcCode76" = "fields.AtcCode76"
"AtcCode77" = "fields.AtcCode77"
"AtcCode78" = "fields.AtcCode78"
"AtcCode79" = "fields.AtcCode79"
"AtcCode80" = "fields.AtcCode80"
"AtcCode81" = "fields.AtcCode81"
"AtcCode82" = "fields.AtcCode82"
"AtcCode83" = "fields.AtcCode83"
"AtcCode84" = "fields.AtcCode84"
"AtcCode85" = "fields.AtcCode85"
"AtcCode86" = "fields.AtcCode86"
"AtcCode87" = "fields.AtcCode87"
"AtcCode88" = "fields.AtcCode88"
"AtcCode89" = "fields.AtcCode89"
"AtcCode90" = "fields.AtcCode90"
"AtcCode91" = "fields.AtcCode91"
"AtcCode92" = "fields.AtcCode92"
"AtcCode93" = "fields.AtcCode93"
"AtcCode94" = "fields.AtcCode94"
"AtcCode95" = "fields.AtcCode95"
"AtcCode96" = "fields.AtcCode96"
"AtcCode97" = "fields.AtcCode97"
"AtcCode98" = "fields.AtcCode98"
"AtcCode99" = "fields.AtcCode99"
"AtcCode100" = "fields.AtcCode100"
"AtcCode101" = "fields.AtcCode101"
"AtcCode102" = "fields.AtcCode102"
"AtcCode103" = "fields.AtcCode103"
"AtcCode104" = "fields.AtcCode104"
"AtcCode105" = "fields.AtcCode105"
"hPartIITableSize" = "fields.hPartIITableSize"
"txtFinalFlag" = "fields.txtFinalFlag"
"txtEnroll" = "fields.txtEnroll"
"ebirOnlineConfirmUsername" = "fields.ebirOnlineConfirmUsername"
"ebirOnlineUsername" = "fields.ebirOnlineUsername"
"ebirOnlineSecret" = "fields.ebirOnlineSecret"
"driveSelectTPExport" = "fields.driveSelectTPExport"
