"txtYear" = "fields.txtYear"
"optQuarter1" = "fields.optQuarter1"
"optQuarter2" = "fields.optQuarter2"
"optQuarter3" = "fields.optQuarter3"
"optQuarter4" = "fields.optQuarter4"
"AmendedRtn_1" = "fields.AmendedRtn_1"
"AmendedRtn_2" = "fields.AmendedRtn_2"
"TaxWithheld_1" = "fields.TaxWithheld_1"
"TaxWithheld_2" = "fields.TaxWithheld_2"
"txtSheets" = "fields.txtSheets"
"txtTIN1" = "fields.txtTIN1"
"txtTIN2" = "fields.txtTIN2"
"txtTIN3" = "fields.txtTIN3"
"txtBranchCode" = "fields.txtBranchCode"
"txtRDOCode" = "fields.txtRDOCode"
"txtTaxpayerName" = "fields.txtTaxpayerName"
"txtAddress" = "fields.txtAddress"
"txtZipCode" = "fields.txtZipCode"
"txtTelNum" = "fields.txtTelNum"
"CatAgent_P" = "fields.CatAgent_P"
"CatAgent_G" = "fields.CatAgent_G"
"txtEmail" = "fields.txtEmail"
"txtATC13" = "fields.txtATC13"
"txtTaxBase13" = "fields.txtTaxBase13"
"txtTaxRate13" = "fields.txtTaxRate13"
"txtTax13" = "fields.txtTax13"
"txtATC14" = "fields.txtATC14"
"txtTaxBase14" = "fields.txtTaxBase14"
"txtTaxRate14" = "fields.txtTaxRate14"
"txtTax14" = "fields.txtTax14"
"txtATC15" = "fields.txtATC15"
"txtTax15" = "fields.txtTax15"
"txtATC16" = "fields.txtATC16"
"txtTax16" = "fields.txtTax16"
"txtATC17" = "fields.txtATC17"
"txtTax17" = "fields.txtTax17"
"txtATC18" = "fields.txtATC18"
"txtTax18" = "fields.txtTax18"
"txtTax19" = "fields.txtTax19"
"txtTax20" = "fields.txtTax20"
"txtTax21" = "fields.txtTax21"
"txtTax22" = "fields.txtTax22"
"txtTax23" = "fields.txtTax23"
"txtTax24" = "fields.txtTax24"
"txtTax25" = "fields.txtTax25"
"txtTax26" = "fields.txtTax26"
"txtTax27" = "fields.txtTax27"
"txtTax28" = "fields.txtTax28"
"txtTax29" = "fields.txtTax29"
"txtTax30" = "fields.txtTax30"
"txtTax31" = "fields.txtTax31"
"optOverRemitRefund" = "fields.optOverRemitRefund"
"optOverRemitTcc" = "fields.optOverRemitTcc"
"optOverRemitCarryOver" = "fields.optOverRemitCarryOver"
"txtAmount32" = "fields.txtAmount32"
"txtAmount33" = "fields.txtAmount33"
"txtAmount34" = "fields.txtAmount34"
"txtParticular35" = "fields.txtParticular35"
"txtAmount35" = "fields.txtAmount35"
