"optCalendar" = "fields.optCalendar"
"optFiscal" = "fields.optFiscal"
"txtYearEnded" = "fields.txtYearEnded"
"optQuarter1" = "fields.optQuarter1"
"optQuarter2" = "fields.optQuarter2"
"optQuarter3" = "fields.optQuarter3"
"optQuarter4" = "fields.optQuarter4"
"txtReturnPeriodFrom" = "fields.txtReturnPeriodFrom"
"txtReturnPeriodTo" = "fields.txtReturnPeriodTo"
"AmendedRtn_1" = "fields.AmendedRtn_1"
"AmendedRtn_2" = "fields.AmendedRtn_2"
"ShortPeriod_1" = "fields.ShortPeriod_1"
"ShortPeriod_2" = "fields.ShortPeriod_2"
"txtTIN1" = "fields.txtTIN1"
"txtTIN2" = "fields.txtTIN2"
"txtTIN3" = "fields.txtTIN3"
"txtBranchCode" = "fields.txtBranchCode"
"txtRDOCode" = "fields.txtRDOCode"
"txtTaxpayerName" = "fields.txtTaxpayerName"
"txtAddress" = "fields.txtAddress"
"txtZipCode" = "fields.txtZipCode"
"txtTelNum" = "fields.txtTelNum"
"txtEmail" = "fields.txtEmail"
"optClassMicro" = "fields.optClassMicro"
"optClassSmall" = "fields.optClassSmall"
"optClassMedium" = "fields.optClassMedium"
"optClassLarge" = "fields.optClassLarge"
"SpecialTax_1" = "fields.SpecialTax_1"
"SpecialTax_2" = "fields.SpecialTax_2"
"txtSpecialTaxDetails" = "fields.txtSpecialTaxDetails"
"txtTax15" = "fields.txtTax15"
"txtTax16" = "fields.txtTax16"
"txtTax17" = "fields.txtTax17"
"txtTax18" = "fields.txtTax18"
"txtOtherCredits19" = "fields.txtOtherCredits19"
"txtTax19" = "fields.txtTax19"
"txtTax20" = "fields.txtTax20"
"txtTax21" = "fields.txtTax21"
"txtTax22" = "fields.txtTax22"
"txtTax23" = "fields.txtTax23"
"txtTax24" = "fields.txtTax24"
"txtTax25" = "fields.txtTax25"
"txtTax26" = "fields.txtTax26"
"txtAmount27" = "fields.txtAmount27"
"txtAmount28" = "fields.txtAmount28"
"txtAmount29" = "fields.txtAmount29"
"txtParticular30" = "fields.txtParticular30"
"txtAmount30" = "fields.txtAmount30"
"txtSales31A" = "fields.txtSales31A"
"txtTax31B" = "fields.txtTax31B"
"txtSales32A" = "fields.txtSales32A"
"txtSales33A" = "fields.txtSales33A"
"txtSales34A" = "fields.txtSales34A"
"txtTax34B" = "fields.txtTax34B"
"txtTax35B" = "fields.txtTax35B"
"txtTax36B" = "fields.txtTax36B"
"txtTax37B" = "fields.txtTax37B"
"txtTax38B" = "fields.txtTax38B"
"txtTax39B" = "fields.txtTax39B"
"txtTax40B" = "fields.txtTax40B"
"txtTax41B" = "fields.txtTax41B"
"txtTax42B" = "fields.txtTax42B"
"txtTax43B" = "fields.txtTax43B"
"txtPurchases44A" = "fields.txtPurchases44A"
"txtTax44B" = "fields.txtTax44B"
"txtPurchases45A" = "fields.txtPurchases45A"
"txtTax45B" = "fields.txtTax45B"
"txtPurchases46A" = "fields.txtPurchases46A"
"txtTax46B" = "fields.txtTax46B"
"txtPurchases47A" = "fields.txtPurchases47A"
"txtTax47B" = "fields.txtTax47B"
"txtPurchases48A" = "fields.txtPurchases48A"
"txtPurchases49A" = "fields.txtPurchases49A"
"txtPurchases50A" = "fields.txtPurchases50A"
"txtTax50B" = "fields.txtTax50B"
"txtTax51B" = "fields.txtTax51B"
"txtTax52B" = "fields.txtTax52B"
"txtTax53B" = "fields.txtTax53B"
"txtTax54B" = "fields.txtTax54B"
"txtTax55B" = "fields.txtTax55B"
"txtTax56B" = "fields.txtTax56B"
"txtTax57B" = "fields.txtTax57B"
"txtTax58B" = "fields.txtTax58B"
"txtTax59B" = "fields.txtTax59B"
"txtTax60B" = "fields.txtTax60B"
"txtTax61B" = "fields.txtTax61B"
