"frm2550qv2024:calendarNo1" = "fields.frm2550qv2024:calendarNo1"
"frm2550qv2024:fiscalNo1" = "fields.frm2550qv2024:fiscalNo1"
"frm2550qv2024:selectedMonthNo2" = "fields.frm2550qv2024:selectedMonthNo2"
"frm2550qv2024:txtYearNo2" = "fields.frm2550qv2024:txtYearNo2"
"frm2550qv2024:OptQuarter1" = "fields.frm2550qv2024:OptQuarter1"
"frm2550qv2024:OptQuarter2" = "fields.frm2550qv2024:OptQuarter2"
"frm2550qv2024:OptQuarter3" = "fields.frm2550qv2024:OptQuarter3"
"frm2550qv2024:OptQuarter4" = "fields.frm2550qv2024:OptQuarter4"
"frm2550qv2024:RtnPeriodFromNo4" = "fields.frm2550qv2024:RtnPeriodFromNo4"
"frm2550qv2024:RtnPeriodToNo4" = "fields.frm2550qv2024:RtnPeriodToNo4"
"frm2550qv2024:amendedReturnYesNo5" = "fields.frm2550qv2024:amendedReturnYesNo5"
"frm2550qv2024:amendedReturnNo5" = "fields.frm2550qv2024:amendedReturnNo5"
"frm2550qv2024:OptShortPrd1" = "fields.frm2550qv2024:OptShortPrd1"
"frm2550qv2024:OptShortPrd2" = "fields.frm2550qv2024:OptShortPrd2"
"frm2550qv2024:txtTIN1" = "fields.frm2550qv2024:txtTIN1"
"frm2550qv2024:txtTIN2" = "fields.frm2550qv2024:txtTIN2"
"frm2550qv2024:txtTIN3" = "fields.frm2550qv2024:txtTIN3"
"frm2550qv2024:branchCode" = "fields.frm2550qv2024:branchCode"
"frm2550qv2024:txtRDOCode" = "fields.frm2550qv2024:txtRDOCode"
"frm2550qv2024:taxpayerName" = "fields.frm2550qv2024:taxpayerName"
"frm2550qv2024:taxpayerAddress" = "fields.frm2550qv2024:taxpayerAddress"
"frm2550qv2024:taxpayerZip" = "fields.frm2550qv2024:taxpayerZip"
"frm2550qv2024:taxpayerContactNumber" = "fields.frm2550qv2024:taxpayerContactNumber"
"frm2550qv2024:taxpayerEmailAddress" = "fields.frm2550qv2024:taxpayerEmailAddress"
"frm2550qv2024:taxPayerClassification1" = "fields.frm2550qv2024:taxPayerClassification1"
"frm2550qv2024:taxPayerClassification2" = "fields.frm2550qv2024:taxPayerClassification2"
"frm2550qv2024:taxPayerClassification3" = "fields.frm2550qv2024:taxPayerClassification3"
"frm2550qv2024:taxPayerClassification4" = "fields.frm2550qv2024:taxPayerClassification4"
"frm2550qv2024:internationalTreatyYn" = "fields.frm2550qv2024:internationalTreatyYn"
"frm2550qv2024:specialRateYn" = "fields.frm2550qv2024:specialRateYn"
"frm2550qv2024:specifyInternationalTreaty" = "fields.frm2550qv2024:specifyInternationalTreaty"
"frm2550qv2024:excessInputTax" = "fields.frm2550qv2024:excessInputTax"
"frm2550qv2024:creditableVat" = "fields.frm2550qv2024:creditableVat"
"frm2550qv2024:advVatPayment" = "fields.frm2550qv2024:advVatPayment"
"frm2550qv2024:vatPaidReturn" = "fields.frm2550qv2024:vatPaidReturn"
"frm2550qv2024:addSpecifyNo19" = "fields.frm2550qv2024:addSpecifyNo19"
"frm2550qv2024:otherCreditsNo19" = "fields.frm2550qv2024:otherCreditsNo19"
"frm2550qv2024:totalTaxCredits" = "fields.frm2550qv2024:totalTaxCredits"
"frm2550qv2024:excessCredits" = "fields.frm2550qv2024:excessCredits"
"frm2550qv2024:surcharge" = "fields.frm2550qv2024:surcharge"
"frm2550qv2024:interest" = "fields.frm2550qv2024:interest"
"frm2550qv2024:compromise" = "fields.frm2550qv2024:compromise"
"frm2550qv2024:penalties" = "fields.frm2550qv2024:penalties"
"frm2550qv2024:totalPayable" = "fields.frm2550qv2024:totalPayable"
"frm2550qv2024:txtPg2TIN1" = "fields.frm2550qv2024:txtPg2TIN1"
"frm2550qv2024:txtPg2TIN2" = "fields.frm2550qv2024:txtPg2TIN2"
"frm2550qv2024:txtPg2TIN3" = "fields.frm2550qv2024:txtPg2TIN3"
"frm2550qv2024:txtPg2BranchCode" = "fields.frm2550qv2024:txtPg2BranchCode"
"frm2550qv2024:Pg2TaxPayer" = "fields.frm2550qv2024:Pg2TaxPayer"
"frm2550qv2024:vatableSales" = "fields.frm2550qv2024:vatableSales"
"frm2550qv2024:outputVatSales" = "fields.frm2550qv2024:outputVatSales"
"frm2550qv2024:zeroRatedSales" = "fields.frm2550qv2024:zeroRatedSales"
"frm2550qv2024:exemptSales" = "fields.frm2550qv2024:exemptSales"
"frm2550qv2024:totalSales" = "fields.frm2550qv2024:totalSales"
"frm2550qv2024:outputTaxDue" = "fields.frm2550qv2024:outputTaxDue"
"frm2550qv2024:lessOutputVat" = "fields.frm2550qv2024:lessOutputVat"
"frm2550qv2024:addOutputVat" = "fields.frm2550qv2024:addOutputVat"
"frm2550qv2024:totalAdjOutput" = "fields.frm2550qv2024:totalAdjOutput"
"frm2550qv2024:inputTaxCarried" = "fields.frm2550qv2024:inputTaxCarried"
"frm2550qv2024:inputTaxDeferred" = "fields.frm2550qv2024:inputTaxDeferred"
"frm2550qv2024:transitionalInputTax" = "fields.frm2550qv2024:transitionalInputTax"
"frm2550qv2024:presumptiveInputTax" = "fields.frm2550qv2024:presumptiveInputTax"
"frm2550qv2024:addSpecifyNo42" = "fields.frm2550qv2024:addSpecifyNo42"
"frm2550qv2024:otherSpecify42" = "fields.frm2550qv2024:otherSpecify42"
"frm2550qv2024:total43" = "fields.frm2550qv2024:total43"
"frm2550qv2024:domesticPurchase" = "fields.frm2550qv2024:domesticPurchase"
"frm2550qv2024:domesticInputTax" = "fields.frm2550qv2024:domesticInputTax"
"frm2550qv2024:servicesPurchase" = "fields.frm2550qv2024:servicesPurchase"
"frm2550qv2024:serviceInputTax" = "fields.frm2550qv2024:serviceInputTax"
"frm2550qv2024:importPurchase" = "fields.frm2550qv2024:importPurchase"
"frm2550qv2024:importInputTax" = "fields.frm2550qv2024:importInputTax"
"frm2550qv2024:addSpecifyNo47" = "fields.frm2550qv2024:addSpecifyNo47"
"frm2550qv2024:otherSpecify47" = "fields.frm2550qv2024:otherSpecify47"
"otherSpecify47B" = "fields.otherSpecify47B"
"frm2550qv2024:domesticPurchaseNoTax" = "fields.frm2550qv2024:domesticPurchaseNoTax"
"frm2550qv2024:vatExemptImports" = "fields.frm2550qv2024:vatExemptImports"
"frm2550qv2024:totalCurPurchase" = "fields.frm2550qv2024:totalCurPurchase"
"frm2550qv2024:totalCurInputTax" = "fields.frm2550qv2024:totalCurInputTax"
"frm2550qv2024:totalAvailInputTax" = "fields.frm2550qv2024:totalAvailInputTax"
"frm2550qv2024:importCapitalInputTax" = "fields.frm2550qv2024:importCapitalInputTax"
"frm2550qv2024:inputTaxAttr" = "fields.frm2550qv2024:inputTaxAttr"
"frm2550qv2024:vatRefund" = "fields.frm2550qv2024:vatRefund"
"frm2550qv2024:inputVatUnpaid" = "fields.frm2550qv2024:inputVatUnpaid"
"frm2550qv2024:addSpecifyNo56" = "fields.frm2550qv2024:addSpecifyNo56"
"frm2550qv2024:otherSpecify56" = "fields.frm2550qv2024:otherSpecify56"
"frm2550qv2024:totalDeductions" = "fields.frm2550qv2024:totalDeductions"
"frm2550qv2024:addInputVat" = "fields.frm2550qv2024:addInputVat"
"frm2550qv2024:adjDeductions" = "fields.frm2550qv2024:adjDeductions"
"frm2550qv2024:totalAllowInputTax" = "fields.frm2550qv2024:totalAllowInputTax"
"frm2550qv2024:netVatPayable" = "fields.frm2550qv2024:netVatPayable"
"txtDatePurchase10" = "fields.txtDatePurchase10"
"txtSourceCode10" = "fields.txtSourceCode10"
"txtDescription10" = "fields.txtDescription10"
"txtAmountPurchase10" = "fields.txtAmountPurchase10"
"txtInputTax10" = "fields.txtInputTax10"
"txtEstimatedLife10" = "fields.txtEstimatedLife10"
"txtRecognizedLife10" = "fields.txtRecognizedLife10"
"txtAllowedInputTax10" = "fields.txtAllowedInputTax10"
"txtBalanceInputTax10" = "fields.txtBalanceInputTax10"
"txtDatePurchase11" = "fields.txtDatePurchase11"
"txtSourceCode11" = "fields.txtSourceCode11"
"txtDescription11" = "fields.txtDescription11"
"txtAmountPurchase11" = "fields.txtAmountPurchase11"
"txtInputTax11" = "fields.txtInputTax11"
"txtEstimatedLife11" = "fields.txtEstimatedLife11"
"txtRecognizedLife11" = "fields.txtRecognizedLife11"
"txtAllowedInputTax11" = "fields.txtAllowedInputTax11"
"txtBalanceInputTax11" = "fields.txtBalanceInputTax11"
"sched1TotalBalPrev" = "fields.sched1TotalBalPrev"
"sched1TotalBalNext" = "fields.sched1TotalBalNext"
"frm2550qv2024:sched2InputTaxDirect" = "fields.frm2550qv2024:sched2InputTaxDirect"
"frm2550qv2024:sched2VatExemptSale" = "fields.frm2550qv2024:sched2VatExemptSale"
"frm2550qv2024:sched2AmountInputTax" = "fields.frm2550qv2024:sched2AmountInputTax"
"frm2550qv2024:sched2TotalSales" = "fields.frm2550qv2024:sched2TotalSales"
"frm2550qv2024:sched2TotalRatable" = "fields.frm2550qv2024:sched2TotalRatable"
"frm2550qv2024:sched2TotalAttr" = "fields.frm2550qv2024:sched2TotalAttr"
"txtDateCovered30" = "fields.txtDateCovered30"
"txtDateCovered3To0" = "fields.txtDateCovered3To0"
"txtNameWithHoldingAgent30" = "fields.txtNameWithHoldingAgent30"
"txtIncomePayment30" = "fields.txtIncomePayment30"
"txtTotalTaxWithHeld30" = "fields.txtTotalTaxWithHeld30"
"txtDateCovered31" = "fields.txtDateCovered31"
"txtDateCovered3To1" = "fields.txtDateCovered3To1"
"txtNameWithHoldingAgent31" = "fields.txtNameWithHoldingAgent31"
"txtIncomePayment31" = "fields.txtIncomePayment31"
"txtTotalTaxWithHeld31" = "fields.txtTotalTaxWithHeld31"
"sched3TotalIncome" = "fields.sched3TotalIncome"
"sched3TotalTax" = "fields.sched3TotalTax"
"txtDate40" = "fields.txtDate40"
"txtDate4To0" = "fields.txtDate4To0"
"txtNameOfMiller40" = "fields.txtNameOfMiller40"
"txtNameOfTaxpayer40" = "fields.txtNameOfTaxpayer40"
"txtOfficialReceiptNumber40" = "fields.txtOfficialReceiptNumber40"
"txtAmountPaid40" = "fields.txtAmountPaid40"
"txtDate41" = "fields.txtDate41"
"txtDate4To1" = "fields.txtDate4To1"
"txtNameOfMiller41" = "fields.txtNameOfMiller41"
"txtNameOfTaxpayer41" = "fields.txtNameOfTaxpayer41"
"txtOfficialReceiptNumber41" = "fields.txtOfficialReceiptNumber41"
"txtAmountPaid41" = "fields.txtAmountPaid41"
"sched4AmountPaid" = "fields.sched4AmountPaid"
"frm2550qv2024:txtCurrentPage" = "fields.frm2550qv2024:txtCurrentPage"
"frm2550qv2024:txtMaxPage" = "fields.frm2550qv2024:txtMaxPage"
"resultOtherCreditsNo19" = "fields.resultOtherCreditsNo19"
"resultOtherCreditsNo42" = "fields.resultOtherCreditsNo42"
"resultOtherCreditsNo47" = "fields.resultOtherCreditsNo47"
"resultOtherCreditsNo56" = "fields.resultOtherCreditsNo56"
"txtTotalAmountOfBalanceofInputTaxFromPrevious" = "fields.txtTotalAmountOfBalanceofInputTaxFromPrevious"
"txtTotalAmountOfBalanceofInputTaxToBeCarried" = "fields.txtTotalAmountOfBalanceofInputTaxToBeCarried"
"txtTotalAmountofIncomePayment" = "fields.txtTotalAmountofIncomePayment"
"txtTotalAmoungOfTaxWithHeld" = "fields.txtTotalAmoungOfTaxWithHeld"
"txtAmountPaidSched4" = "fields.txtAmountPaidSched4"
"txtFinalFlag" = "fields.txtFinalFlag"
"txtEnroll" = "fields.txtEnroll"
"ebirOnlineConfirmUsername" = "fields.ebirOnlineConfirmUsername"
"ebirOnlineUsername" = "fields.ebirOnlineUsername"
"ebirOnlineSecret" = "fields.ebirOnlineSecret"
"txtEmail" = "fields.txtEmail"
"driveSelectTPExport" = "fields.driveSelectTPExport"
"dateFiled" = "fields.dateFiled"
