"frm0619E:txtMonth" = "fields.frm0619E:txtMonth"
"frm0619E:txtYear" = "fields.frm0619E:txtYear"
"frm0619E:txtDueMonth" = "fields.frm0619E:txtDueMonth"
"frm0619E:txtDueDay" = "fields.frm0619E:txtDueDay"
"frm0619E:txtDueYear" = "fields.frm0619E:txtDueYear"
"frm0619E:optAmend:Y" = "fields.frm0619E:optAmend:Y"
"frm0619E:optAmend:N" = "fields.frm0619E:optAmend:N"
"frm0619E:optWithheld:Y" = "fields.frm0619E:optWithheld:Y"
"frm0619E:optWithheld:N" = "fields.frm0619E:optWithheld:N"
"frm0619E:txtAtc" = "fields.frm0619E:txtAtc"
"frm0619E:txtTaxTypeCode" = "fields.frm0619E:txtTaxTypeCode"
"frm0619E:txtTIN1" = "fields.frm0619E:txtTIN1"
"frm0619E:txtTIN2" = "fields.frm0619E:txtTIN2"
"frm0619E:txtTIN3" = "fields.frm0619E:txtTIN3"
"frm0619E:txtBranchCode" = "fields.frm0619E:txtBranchCode"
"frm0619E:txtRDOCode" = "fields.frm0619E:txtRDOCode"
"frm0619E:txtTaxpayerName" = "fields.frm0619E:txtTaxpayerName"
"frm0619E:txtLineBus" = "fields.frm0619E:txtLineBus"
"frm0619E:txtAddress" = "fields.frm0619E:txtAddress"
"frm0619E:txtZipCode" = "fields.frm0619E:txtZipCode"
"frm0619E:txtTelNum" = "fields.frm0619E:txtTelNum"
"frm0619E:optCategory:P" = "fields.frm0619E:optCategory:P"
"frm0619E:optCategory:G" = "fields.frm0619E:optCategory:G"
"txtEmail" = "fields.txtEmail"
"frm0619E:txtTax14" = "fields.frm0619E:txtTax14"
"frm0619E:txtTax15" = "fields.frm0619E:txtTax15"
"frm0619E:txtTax16" = "fields.frm0619E:txtTax16"
"frm0619E:txtTax17A" = "fields.frm0619E:txtTax17A"
"frm0619E:txtTax17B" = "fields.frm0619E:txtTax17B"
"frm0619E:txtTax17C" = "fields.frm0619E:txtTax17C"
"frm0619E:txtTax17D" = "fields.frm0619E:txtTax17D"
"frm0619E:txtTax18" = "fields.frm0619E:txtTax18"
"txtTaxAgentNo" = "fields.txtTaxAgentNo"
"txtDateIssue" = "fields.txtDateIssue"
"txtDateExpiry" = "fields.txtDateExpiry"
"txtAgency19" = "fields.txtAgency19"
"txtNumber19" = "fields.txtNumber19"
"txtDate19" = "fields.txtDate19"
"txtAmount19" = "fields.txtAmount19"
"txtAgency20" = "fields.txtAgency20"
"txtNumber20" = "fields.txtNumber20"
"txtDate20" = "fields.txtDate20"
"txtAmount20" = "fields.txtAmount20"
"txtAgency21" = "fields.txtAgency21"
"txtNumber21" = "fields.txtNumber21"
"txtDate21" = "fields.txtDate21"
"txtAmount21" = "fields.txtAmount21"
"txtParticular22" = "fields.txtParticular22"
"txtAgency22" = "fields.txtAgency22"
"txtNumber22" = "fields.txtNumber22"
"txtDate22" = "fields.txtDate22"
"txtAmount22" = "fields.txtAmount22"
"txtFinalFlag" = "fields.txtFinalFlag"
"txtEnroll" = "fields.txtEnroll"
"ebirOnlineConfirmUsername" = "fields.ebirOnlineConfirmUsername"
"ebirOnlineUsername" = "fields.ebirOnlineUsername"
"ebirOnlineSecret" = "fields.ebirOnlineSecret"
"driveSelectTPExport" = "fields.driveSelectTPExport"
