"txtMonthYear" = "fields.txtMonthYear"
"txtDueDate" = "fields.txtDueDate"
"AmendedRtn_1" = "fields.AmendedRtn_1"
"AmendedRtn_2" = "fields.AmendedRtn_2"
"TaxWithheld_1" = "fields.TaxWithheld_1"
"TaxWithheld_2" = "fields.TaxWithheld_2"
"txtATC" = "fields.txtATC"
"txtTaxType" = "fields.txtTaxType"
"txtTIN1" = "fields.txtTIN1"
"txtTIN2" = "fields.txtTIN2"
"txtTIN3" = "fields.txtTIN3"
"txtBranchCode" = "fields.txtBranchCode"
"txtRDOCode" = "fields.txtRDOCode"
"txtTaxpayerName" = "fields.txtTaxpayerName"
"txtAddress" = "fields.txtAddress"
"txtZipCode" = "fields.txtZipCode"
"txtTelNum" = "fields.txtTelNum"
"CatAgent_P" = "fields.CatAgent_P"
"CatAgent_G" = "fields.CatAgent_G"
"txtEmail" = "fields.txtEmail"
"txtTax14" = "fields.txtTax14"
"txtTax15" = "fields.txtTax15"
"txtTax16" = "fields.txtTax16"
"txtTax17A" = "fields.txtTax17A"
"txtTax17B" = "fields.txtTax17B"
"txtTax17C" = "fields.txtTax17C"
"txtTax17D" = "fields.txtTax17D"
"txtTax18" = "fields.txtTax18"
"txtAgency19" = "fields.txtAgency19"
"txtNumber19" = "fields.txtNumber19"
"txtDate19" = "fields.txtDate19"
"txtAmount19" = "fields.txtAmount19"
"txtAgency20" = "fields.txtAgency20"
"txtNumber20" = "fields.txtNumber20"
"txtDate20" = "fields.txtDate20"
"txtAmount20" = "fields.txtAmount20"
"txtNumber21" = "fields.txtNumber21"
"txtDate21" = "fields.txtDate21"
"txtAmount21" = "fields.txtAmount21"
"txtParticular22" = "fields.txtParticular22"
"txtAmount22" = "fields.txtAmount22"
