"frm1701q:txtYear" = "fields.frm1701q:txtYear"
"frm1701q:DateQuarter_1" = "fields.frm1701q:DateQuarter_1"
"frm1701q:DateQuarter_2" = "fields.frm1701q:DateQuarter_2"
"frm1701q:DateQuarter_3" = "fields.frm1701q:DateQuarter_3"
"frm1701q:AmendedRtn_1" = "fields.frm1701q:AmendedRtn_1"
"frm1701q:AmendedRtn_2" = "fields.frm1701q:AmendedRtn_2"
"frm1701q:txtSheets" = "fields.frm1701q:txtSheets"
"frm1701q:txt5TIN1" = "fields.frm1701q:txt5TIN1"
"frm1701q:txt5TIN2" = "fields.frm1701q:txt5TIN2"
"frm1701q:txt5TIN3" = "fields.frm1701q:txt5TIN3"
"frm1701q:txt5BranchCode" = "fields.frm1701q:txt5BranchCode"
"frm1701q:txt5RDOCode" = "fields.frm1701q:txt5RDOCode"
"frm1701q:txt7TIN1" = "fields.frm1701q:txt7TIN1"
"frm1701q:txt7TIN2" = "fields.frm1701q:txt7TIN2"
"frm1701q:txt7TIN3" = "fields.frm1701q:txt7TIN3"
"frm1701q:txt7BranchCode" = "fields.frm1701q:txt7BranchCode"
"frm1701q:txt7RDOCode" = "fields.frm1701q:txt7RDOCode"
"frm1701q:txtTaxPayername" = "fields.frm1701q:txtTaxPayername"
"frm1701q:txtSpousename" = "fields.frm1701q:txtSpousename"
"frm1701q:txt11Address" = "fields.frm1701q:txt11Address"
"frm1701q:txt12Address" = "fields.frm1701q:txt12Address"
"frm1701q:txt13BirthMonth" = "fields.frm1701q:txt13BirthMonth"
"frm1701q:txt13BirthDay" = "fields.frm1701q:txt13BirthDay"
"frm1701q:txt13BirthYear" = "fields.frm1701q:txt13BirthYear"
"frm1701q:txt14zip" = "fields.frm1701q:txt14zip"
"frm1701q:txt15Telno" = "fields.frm1701q:txt15Telno"
"frm1701q:txt16BirthMonth" = "fields.frm1701q:txt16BirthMonth"
"frm1701q:txt16BirthDay" = "fields.frm1701q:txt16BirthDay"
"frm1701q:txt16BirthYear" = "fields.frm1701q:txt16BirthYear"
"frm1701q:txt17" = "fields.frm1701q:txt17"
"frm1701q:txt18Telno" = "fields.frm1701q:txt18Telno"
"frm1701q:txt19" = "fields.frm1701q:txt19"
"frm1701q:txt20A" = "fields.frm1701q:txt20A"
"frm1701q:optATC20_1" = "fields.frm1701q:optATC20_1"
"frm1701q:txt20B" = "fields.frm1701q:txt20B"
"frm1701q:optATC20_2" = "fields.frm1701q:optATC20_2"
"frm1701q:txt20C" = "fields.frm1701q:txt20C"
"frm1701q:optATC20_3" = "fields.frm1701q:optATC20_3"
"frm1701q:txt21" = "fields.frm1701q:txt21"
"frm1701q:txt22A" = "fields.frm1701q:txt22A"
"frm1701q:optATC22_1" = "fields.frm1701q:optATC22_1"
"frm1701q:txt22B" = "fields.frm1701q:txt22B"
"frm1701q:optATC22_2" = "fields.frm1701q:optATC22_2"
"frm1701q:txt22C" = "fields.frm1701q:txt22C"
"frm1701q:optATC22_3" = "fields.frm1701q:optATC22_3"
"frm1701:optMethodOfDeduction23:_1" = "fields.frm1701:optMethodOfDeduction23:_1"
"frm1701:optMethodOfDeduction23:_2" = "fields.frm1701:optMethodOfDeduction23:_2"
"frm1701:optMethodOfDeduction24:_1" = "fields.frm1701:optMethodOfDeduction24:_1"
"frm1701:optMethodOfDeduction24:_2" = "fields.frm1701:optMethodOfDeduction24:_2"
"frm1701q:SelTreaty_1" = "fields.frm1701q:SelTreaty_1"
"frm1701q:SelTreaty_2" = "fields.frm1701q:SelTreaty_2"
"frm1701q:txtTaxRelief25" = "fields.frm1701q:txtTaxRelief25"
"frm1701q:txt26A" = "fields.frm1701q:txt26A"
"frm1701q:txt26B" = "fields.frm1701q:txt26B"
"frm1701q:txt27A" = "fields.frm1701q:txt27A"
"frm1701q:txt27B" = "fields.frm1701q:txt27B"
"frm1701q:txt28A" = "fields.frm1701q:txt28A"
"frm1701q:txt28B" = "fields.frm1701q:txt28B"
"frm1701q:txt29A" = "fields.frm1701q:txt29A"
"frm1701q:txt29B" = "fields.frm1701q:txt29B"
"frm1701q:txt30A" = "fields.frm1701q:txt30A"
"frm1701q:txt30B" = "fields.frm1701q:txt30B"
"frm1701q:txt31A" = "fields.frm1701q:txt31A"
"frm1701q:txt31B" = "fields.frm1701q:txt31B"
"frm1701q:txt32A" = "fields.frm1701q:txt32A"
"frm1701q:txt32B" = "fields.frm1701q:txt32B"
"frm1701q:txt33A" = "fields.frm1701q:txt33A"
"frm1701q:txt33B" = "fields.frm1701q:txt33B"
"frm1701q:txt34A" = "fields.frm1701q:txt34A"
"frm1701q:txt34B" = "fields.frm1701q:txt34B"
"frm1701q:txt35A" = "fields.frm1701q:txt35A"
"frm1701q:txt35B" = "fields.frm1701q:txt35B"
"frm1701q:txt36A" = "fields.frm1701q:txt36A"
"frm1701q:txt36B" = "fields.frm1701q:txt36B"
"frm1701q:txt37A" = "fields.frm1701q:txt37A"
"frm1701q:txt37B" = "fields.frm1701q:txt37B"
"frm1701q:txt38A" = "fields.frm1701q:txt38A"
"frm1701q:txt38B" = "fields.frm1701q:txt38B"
"frm1701q:txt38C" = "fields.frm1701q:txt38C"
"frm1701q:txt38D" = "fields.frm1701q:txt38D"
"frm1701q:txt38E" = "fields.frm1701q:txt38E"
"frm1701q:txt38F" = "fields.frm1701q:txt38F"
"frm1701q:txt38G" = "fields.frm1701q:txt38G"
"frm1701q:txt38H" = "fields.frm1701q:txt38H"
"frm1701q:txt38I" = "fields.frm1701q:txt38I"
"frm1701q:txt38J" = "fields.frm1701q:txt38J"
"frm1701q:txt38K" = "fields.frm1701q:txt38K"
"frm1701q:txt38L" = "fields.frm1701q:txt38L"
"frm1701q:txt38M" = "fields.frm1701q:txt38M"
"frm1701q:txt38N" = "fields.frm1701q:txt38N"
"frm1701q:txt39A" = "fields.frm1701q:txt39A"
"frm1701q:txt39B" = "fields.frm1701q:txt39B"
"frm1701q:txt40A" = "fields.frm1701q:txt40A"
"frm1701q:txt40B" = "fields.frm1701q:txt40B"
"frm1701q:txt40C" = "fields.frm1701q:txt40C"
"frm1701q:txt40D" = "fields.frm1701q:txt40D"
"frm1701q:txt40E" = "fields.frm1701q:txt40E"
"frm1701q:txt40F" = "fields.frm1701q:txt40F"
"frm1701q:txt40G" = "fields.frm1701q:txt40G"
"frm1701q:txt40H" = "fields.frm1701q:txt40H"
"frm1701q:txt41A" = "fields.frm1701q:txt41A"
"frm1701q:txt41B" = "fields.frm1701q:txt41B"
"frm1701q:txt41C" = "fields.frm1701q:txt41C"
"txtFinalFlag" = "fields.txtFinalFlag"
"txtEnroll" = "fields.txtEnroll"
"ebirOnlineConfirmUsername" = "fields.ebirOnlineConfirmUsername"
"ebirOnlineUsername" = "fields.ebirOnlineUsername"
"ebirOnlineSecret" = "fields.ebirOnlineSecret"
"txtEmail" = "fields.txtEmail"
"driveSelectTPExport" = "fields.driveSelectTPExport"
