"optCalendar" = "fields.optCalendar"
"optFiscal" = "fields.optFiscal"
"txtYearEnded" = "fields.txtYearEnded"
"optQuarter1" = "fields.optQuarter1"
"optQuarter2" = "fields.optQuarter2"
"optQuarter3" = "fields.optQuarter3"
"AmendedRtn_1" = "fields.AmendedRtn_1"
"AmendedRtn_2" = "fields.AmendedRtn_2"
"txtATC" = "fields.txtATC"
"txtTIN1" = "fields.txtTIN1"
"txtTIN2" = "fields.txtTIN2"
"txtTIN3" = "fields.txtTIN3"
"txtBranchCode" = "fields.txtBranchCode"
"txtRDOCode" = "fields.txtRDOCode"
"txtTaxpayerName" = "fields.txtTaxpayerName"
"txtAddress" = "fields.txtAddress"
"txtZipCode" = "fields.txtZipCode"
"txtTelNum" = "fields.txtTelNum"
"txtEmail" = "fields.txtEmail"
"optItemizedDeductions" = "fields.optItemizedDeductions"
"optOptionalStandardDeduction" = "fields.optOptionalStandardDeduction"
"SpecialTax_1" = "fields.SpecialTax_1"
"SpecialTax_2" = "fields.SpecialTax_2"
"txtSpecialTaxDetails" = "fields.txtSpecialTaxDetails"
"txtTax14" = "fields.txtTax14"
"txtTax15" = "fields.txtTax15"
"txtTax16" = "fields.txtTax16"
"txtTax17" = "fields.txtTax17"
"txtTax18" = "fields.txtTax18"
"txtTax19" = "fields.txtTax19"
"txtTax20" = "fields.txtTax20"
"txtTax21" = "fields.txtTax21"
"txtTax22" = "fields.txtTax22"
"txtTax23" = "fields.txtTax23"
"txtTax24" = "fields.txtTax24"
"txtTax25" = "fields.txtTax25"
"txtSheets" = "fields.txtSheets"
"txtAmount27" = "fields.txtAmount27"
"txtAmount28" = "fields.txtAmount28"
"txtAmount29" = "fields.txtAmount29"
"txtParticular30" = "fields.txtParticular30"
"txtAmount30" = "fields.txtAmount30"
"sched1:txtSales1" = "fields.sched1_txtSales1"
"sched1:txtCost2" = "fields.sched1_txtCost2"
"sched1:txtGross3" = "fields.sched1_txtGross3"
"sched1:txtOtherIncome4" = "fields.sched1_txtOtherIncome4"
"sched1:txtTotalGross5" = "fields.sched1_txtTotalGross5"
"sched1:txtDeductions6" = "fields.sched1_txtDeductions6"
"sched1:txtTaxable7" = "fields.sched1_txtTaxable7"
"sched1:txtPrevious8" = "fields.sched1_txtPrevious8"
"sched1:txtTotalTaxable9" = "fields.sched1_txtTotalTaxable9"
"sched1:txtRate10" = "fields.sched1_txtRate10"
"sched1:txtTaxDue11" = "fields.sched1_txtTaxDue11"
"sched1:txtShare12" = "fields.sched1_txtShare12"
"sched1:txtNetTax13" = "fields.sched1_txtNetTax13"
"sched2:txtSales1" = "fields.sched2_txtSales1"
"sched2:txtTaxDue13" = "fields.sched2_txtTaxDue13"
"sched3:txtGross1" = "fields.sched3_txtGross1"
"sched3:txtGross2" = "fields.sched3_txtGross2"
"sched3:txtGross3" = "fields.sched3_txtGross3"
"sched3:txtTotal4" = "fields.sched3_txtTotal4"
"sched3:txtRate5" = "fields.sched3_txtRate5"
"sched3:txtMcit6" = "fields.sched3_txtMcit6"
"sched4:txtPriorYearCredits1" = "fields.sched4_txtPriorYearCredits1"
"sched4:txtPreviousPayments2" = "fields.sched4_txtPreviousPayments2"
"sched4:txtMcitPayments3" = "fields.sched4_txtMcitPayments3"
"sched4:txtCwtPrevious4" = "fields.sched4_txtCwtPrevious4"
"sched4:txtCwtCurrent5" = "fields.sched4_txtCwtCurrent5"
"sched4:txtPriorReturnTax6" = "fields.sched4_txtPriorReturnTax6"
"sched4:txtTotal7" = "fields.sched4_txtTotal7"
