"frm1702q:rbForClndrFscl_1" = "fields.frm1702q:rbForClndrFscl_1"
"frm1702q:rbForClndrFscl_2" = "fields.frm1702q:rbForClndrFscl_2"
"frm1702q:rbYrEndMonth" = "fields.frm1702q:rbYrEndMonth"
"frm1702q:txtYrEndYear" = "fields.frm1702q:txtYrEndYear"
"frm1702q:rbQuarter_1" = "fields.frm1702q:rbQuarter_1"
"frm1702q:rbQuarter_2" = "fields.frm1702q:rbQuarter_2"
"frm1702q:rbQuarter_3" = "fields.frm1702q:rbQuarter_3"
"frm1702q:rbAmendedRtn_1" = "fields.frm1702q:rbAmendedRtn_1"
"frm1702q:rbAmendedRtn_2" = "fields.frm1702q:rbAmendedRtn_2"
"frm1702q:txtATC_1" = "fields.frm1702q:txtATC_1"
"frm1702q:rbATC_1" = "fields.frm1702q:rbATC_1"
"frm1702q:cbATC_2" = "fields.frm1702q:cbATC_2"
"frm1702q:rbATC_2" = "fields.frm1702q:rbATC_2"
"frm1702q:txtTIN1" = "fields.frm1702q:txtTIN1"
"frm1702q:txtTIN2" = "fields.frm1702q:txtTIN2"
"frm1702q:txtTIN3" = "fields.frm1702q:txtTIN3"
"frm1702q:txtBranchCode" = "fields.frm1702q:txtBranchCode"
"frm1702q:txtRDOCode" = "fields.frm1702q:txtRDOCode"
"frm1702q:txtTaxpayerName1" = "fields.frm1702q:txtTaxpayerName1"
"frm1702q:txtAddress" = "fields.frm1702q:txtAddress"
"frm1702q:txtZipCode" = "fields.frm1702q:txtZipCode"
"frm1702q:txtTelNum" = "fields.frm1702q:txtTelNum"
"txtEmail" = "fields.txtEmail"
"frm1702q:rbMthdOfDdctns_1" = "fields.frm1702q:rbMthdOfDdctns_1"
"frm1702q:rbMthdOfDdctns_2" = "fields.frm1702q:rbMthdOfDdctns_2"
"frm1702q:rbTxRlf_1" = "fields.frm1702q:rbTxRlf_1"
"frm1702q:rbTxRlf_2" = "fields.frm1702q:rbTxRlf_2"
"frm1702q:txtTxRlfSpcfy" = "fields.frm1702q:txtTxRlfSpcfy"
"frm1702q:txtTax14" = "fields.frm1702q:txtTax14"
"frm1702q:txtTax15" = "fields.frm1702q:txtTax15"
"frm1702q:txtTax16" = "fields.frm1702q:txtTax16"
"frm1702q:txtTax17" = "fields.frm1702q:txtTax17"
"frm1702q:txtTax18" = "fields.frm1702q:txtTax18"
"frm1702q:txtTax19" = "fields.frm1702q:txtTax19"
"frm1702q:txtTax20" = "fields.frm1702q:txtTax20"
"frm1702q:txtTax21" = "fields.frm1702q:txtTax21"
"frm1702q:txtTax22" = "fields.frm1702q:txtTax22"
"frm1702q:txtTax23" = "fields.frm1702q:txtTax23"
"frm1702q:txtTax24" = "fields.frm1702q:txtTax24"
"frm1702q:txtTax25" = "fields.frm1702q:txtTax25"
"frm1702q:txtSheets" = "fields.frm1702q:txtSheets"
"frm1702q:txtPg2TIN1" = "fields.frm1702q:txtPg2TIN1"
"frm1702q:txtPg2TIN2" = "fields.frm1702q:txtPg2TIN2"
"frm1702q:txtPg2TIN3" = "fields.frm1702q:txtPg2TIN3"
"frm1702q:txtPg2BranchCode" = "fields.frm1702q:txtPg2BranchCode"
"frm1702q:txtPg2TaxpayerName" = "fields.frm1702q:txtPg2TaxpayerName"
"frm1702q:Sched1:txtTax1A" = "fields.frm1702q:Sched1:txtTax1A"
"frm1702q:Sched1:txtTax1B" = "fields.frm1702q:Sched1:txtTax1B"
"frm1702q:Sched1:txtTax2A" = "fields.frm1702q:Sched1:txtTax2A"
"frm1702q:Sched1:txtTax2B" = "fields.frm1702q:Sched1:txtTax2B"
"frm1702q:Sched1:txtTax3A" = "fields.frm1702q:Sched1:txtTax3A"
"frm1702q:Sched1:txtTax3B" = "fields.frm1702q:Sched1:txtTax3B"
"frm1702q:Sched1:txtTax4A" = "fields.frm1702q:Sched1:txtTax4A"
"frm1702q:Sched1:txtTax4B" = "fields.frm1702q:Sched1:txtTax4B"
"frm1702q:Sched1:txtTax5A" = "fields.frm1702q:Sched1:txtTax5A"
"frm1702q:Sched1:txtTax5B" = "fields.frm1702q:Sched1:txtTax5B"
"frm1702q:Sched1:txtTax6A" = "fields.frm1702q:Sched1:txtTax6A"
"frm1702q:Sched1:txtTax6B" = "fields.frm1702q:Sched1:txtTax6B"
"frm1702q:Sched1:txtTax7A" = "fields.frm1702q:Sched1:txtTax7A"
"frm1702q:Sched1:txtTax7B" = "fields.frm1702q:Sched1:txtTax7B"
"frm1702q:Sched1:txtTax8A" = "fields.frm1702q:Sched1:txtTax8A"
"frm1702q:Sched1:txtTax8B" = "fields.frm1702q:Sched1:txtTax8B"
"frm1702q:Sched1:txtTax9A" = "fields.frm1702q:Sched1:txtTax9A"
"frm1702q:Sched1:txtTax9B" = "fields.frm1702q:Sched1:txtTax9B"
"frm1702q:Sched1:txtTax10A" = "fields.frm1702q:Sched1:txtTax10A"
"frm1702q:Sched1:txtTax10B" = "fields.frm1702q:Sched1:txtTax10B"
"frm1702q:Sched1:txtTax11A" = "fields.frm1702q:Sched1:txtTax11A"
"frm1702q:Sched1:txtTax11B" = "fields.frm1702q:Sched1:txtTax11B"
"frm1702q:Sched1:txtTax12B" = "fields.frm1702q:Sched1:txtTax12B"
"frm1702q:Sched1:txtTax13B" = "fields.frm1702q:Sched1:txtTax13B"
"frm1702q:Sched2:txtTax1" = "fields.frm1702q:Sched2:txtTax1"
"frm1702q:Sched2:txtTax2" = "fields.frm1702q:Sched2:txtTax2"
"frm1702q:Sched2:txtTax3" = "fields.frm1702q:Sched2:txtTax3"
"frm1702q:Sched2:txtTax4" = "fields.frm1702q:Sched2:txtTax4"
"frm1702q:Sched2:txtTax5" = "fields.frm1702q:Sched2:txtTax5"
"frm1702q:Sched2:txtTax6" = "fields.frm1702q:Sched2:txtTax6"
"frm1702q:Sched2:txtTax7" = "fields.frm1702q:Sched2:txtTax7"
"frm1702q:Sched2:txtTax8" = "fields.frm1702q:Sched2:txtTax8"
"frm1702q:Sched2:txtTax9" = "fields.frm1702q:Sched2:txtTax9"
"frm1702q:Sched2:txtTax10" = "fields.frm1702q:Sched2:txtTax10"
"frm1702q:Sched2:txtTax11" = "fields.frm1702q:Sched2:txtTax11"
"frm1702q:Sched2:txtTax12" = "fields.frm1702q:Sched2:txtTax12"
"frm1702q:Sched2:txtTax13" = "fields.frm1702q:Sched2:txtTax13"
"frm1702q:Sched3:txtTax1" = "fields.frm1702q:Sched3:txtTax1"
"frm1702q:Sched3:txtTax2" = "fields.frm1702q:Sched3:txtTax2"
"frm1702q:Sched3:txtTax3" = "fields.frm1702q:Sched3:txtTax3"
"frm1702q:Sched3:txtTax4" = "fields.frm1702q:Sched3:txtTax4"
"frm1702q:Sched3:txtTax5" = "fields.frm1702q:Sched3:txtTax5"
"frm1702q:Sched3:txtTax6" = "fields.frm1702q:Sched3:txtTax6"
"frm1702q:Sched4:txtTax1" = "fields.frm1702q:Sched4:txtTax1"
"frm1702q:Sched4:txtTax2" = "fields.frm1702q:Sched4:txtTax2"
"frm1702q:Sched4:txtTax3" = "fields.frm1702q:Sched4:txtTax3"
"frm1702q:Sched4:txtTax4" = "fields.frm1702q:Sched4:txtTax4"
"frm1702q:Sched4:txtTax5" = "fields.frm1702q:Sched4:txtTax5"
"frm1702q:Sched4:txtTax6" = "fields.frm1702q:Sched4:txtTax6"
"frm1702q:Sched4:chkOthrTxCrdts0" = "fields.frm1702q:Sched4:chkOthrTxCrdts0"
"frm1702q:Sched4:txtOthrTxCrdts0" = "fields.frm1702q:Sched4:txtOthrTxCrdts0"
"frm1702q:Sched4:txtOthrTxCrdtAmnt0" = "fields.frm1702q:Sched4:txtOthrTxCrdtAmnt0"
"frm1702q:Sched4:chkOthrTxCrdts1" = "fields.frm1702q:Sched4:chkOthrTxCrdts1"
"frm1702q:Sched4:txtOthrTxCrdts1" = "fields.frm1702q:Sched4:txtOthrTxCrdts1"
"frm1702q:Sched4:txtOthrTxCrdtAmnt1" = "fields.frm1702q:Sched4:txtOthrTxCrdtAmnt1"
"frm1702q:Sched4:txtTax7" = "fields.frm1702q:Sched4:txtTax7"
"frm1702q:txtCurrentPage" = "fields.frm1702q:txtCurrentPage"
"frm1702q:txtMaxPage" = "fields.frm1702q:txtMaxPage"
"resultOtherSpecify" = "fields.resultOtherSpecify"
"txtFinalFlag" = "fields.txtFinalFlag"
"txtEnroll" = "fields.txtEnroll"
"ebirOnlineConfirmUsername" = "fields.ebirOnlineConfirmUsername"
"ebirOnlineUsername" = "fields.ebirOnlineUsername"
"ebirOnlineSecret" = "fields.ebirOnlineSecret"
"frm1702q:txtLOB" = "fields.frm1702q:txtLOB"
"driveSelectTPExport" = "fields.driveSelectTPExport"
