"txtMonth" = "fields.txtMonth"
"txtYear" = "fields.txtYear"
"AmendedRtn_1" = "fields.AmendedRtn_1"
"AmendedRtn_2" = "fields.AmendedRtn_2"
"TaxWithheld_1" = "fields.TaxWithheld_1"
"TaxWithheld_2" = "fields.TaxWithheld_2"
"txtSheets" = "fields.txtSheets"
"txtATC" = "fields.txtATC"
"txtTIN1" = "fields.txtTIN1"
"txtTIN2" = "fields.txtTIN2"
"txtTIN3" = "fields.txtTIN3"
"txtBranchCode" = "fields.txtBranchCode"
"txtRDOCode" = "fields.txtRDOCode"
"txtTaxpayerName" = "fields.txtTaxpayerName"
"txtAddress" = "fields.txtAddress"
"txtAddress2" = "fields.txtAddress2"
"txtZipCode" = "fields.txtZipCode"
"txtTelNum" = "fields.txtTelNum"
"CatAgent_P" = "fields.CatAgent_P"
"CatAgent_G" = "fields.CatAgent_G"
"SpecialTax_1" = "fields.SpecialTax_1"
"SpecialTax_2" = "fields.SpecialTax_2"
"selTreaty" = "fields.selTreaty"
"txtTax14" = "fields.txtTax14"
"txtTax15" = "fields.txtTax15"
"txtTax16" = "fields.txtTax16"
"txtTax17" = "fields.txtTax17"
"txtTax18" = "fields.txtTax18"
"txtTax19" = "fields.txtTax19"
"txt20Other" = "fields.txt20Other"
"txtTax20" = "fields.txtTax20"
"txtTax21" = "fields.txtTax21"
"txtTax22" = "fields.txtTax22"
"txtTax23" = "fields.txtTax23"
"txtTax24" = "fields.txtTax24"
"txtTax25" = "fields.txtTax25"
"txtTax26" = "fields.txtTax26"
"txtTax27" = "fields.txtTax27"
"txtTax28" = "fields.txtTax28"
"txt29Other" = "fields.txt29Other"
"txtTax29" = "fields.txtTax29"
"txtTax30" = "fields.txtTax30"
"txtTax31" = "fields.txtTax31"
"txtTax32" = "fields.txtTax32"
"txtTax33" = "fields.txtTax33"
"txtTax34" = "fields.txtTax34"
"txtTax35" = "fields.txtTax35"
"txtTax36" = "fields.txtTax36"
"txtAgency37" = "fields.txtAgency37"
"txtNumber37" = "fields.txtNumber37"
"txtDate37" = "fields.txtDate37"
"txtAmount37" = "fields.txtAmount37"
"txtAgency38" = "fields.txtAgency38"
"txtNumber38" = "fields.txtNumber38"
"txtDate38" = "fields.txtDate38"
"txtAmount38" = "fields.txtAmount38"
"txtNumber39" = "fields.txtNumber39"
"txtDate39" = "fields.txtDate39"
"txtAmount39" = "fields.txtAmount39"
"txtParticular40" = "fields.txtParticular40"
"txtAgency40" = "fields.txtAgency40"
"txtNumber40" = "fields.txtNumber40"
"txtDate40" = "fields.txtDate40"
"txtAmount40" = "fields.txtAmount40"
"txtPg2TIN1" = "fields.txtPg2TIN1"
"txtPg2TIN2" = "fields.txtPg2TIN2"
"txtPg2TIN3" = "fields.txtPg2TIN3"
"txtPg2BranchCode" = "fields.txtPg2BranchCode"
"txtPg2TaxpayerName" = "fields.txtPg2TaxpayerName"
"sched1:txtTotal1" = "fields.sched1:txtTotal1"
"txtCurrentPage" = "fields.txtCurrentPage"
"txtMaxPage" = "fields.txtMaxPage"
"txtLineBus" = "fields.txtLineBus"
