"frm2000:txtMonth" = "fields.frm2000:txtMonth"
"frm2000:txtYear" = "fields.frm2000:txtYear"
"frm2000:AmendedRtn_1" = "fields.frm2000:AmendedRtn_1"
"frm2000:AmendedRtn_2" = "fields.frm2000:AmendedRtn_2"
"frm2000:txtSheets" = "fields.frm2000:txtSheets"
"frm2000:txtTIN1" = "fields.frm2000:txtTIN1"
"frm2000:txtTIN2" = "fields.frm2000:txtTIN2"
"frm2000:txtTIN3" = "fields.frm2000:txtTIN3"
"frm2000:txtBranchCode" = "fields.frm2000:txtBranchCode"
"frm2000:txtRDOCode" = "fields.frm2000:txtRDOCode"
"frm2000:txtTaxpayerName" = "fields.frm2000:txtTaxpayerName"
"frm2000:txtAddress" = "fields.frm2000:txtAddress"
"frm2000:txtZipCode" = "fields.frm2000:txtZipCode"
"frm2000:txtTelNum" = "fields.frm2000:txtTelNum"
"txtEmail" = "fields.txtEmail"
"frm2000:optParty_1" = "fields.frm2000:optParty_1"
"frm2000:optParty_2" = "fields.frm2000:optParty_2"
"frm2000:optParty_3" = "fields.frm2000:optParty_3"
"frm2000:txtOtherName" = "fields.frm2000:txtOtherName"
"frm2000:txtOtherTIN" = "fields.frm2000:txtOtherTIN"
"frm2000:optMode_1" = "fields.frm2000:optMode_1"
"frm2000:optMode_2" = "fields.frm2000:optMode_2"
"frm2000:optMode_3" = "fields.frm2000:optMode_3"
"frm2000:txtTax14" = "fields.frm2000:txtTax14"
"frm2000:txtTax15A" = "fields.frm2000:txtTax15A"
"frm2000:txtTax15B" = "fields.frm2000:txtTax15B"
"frm2000:txtTax15C" = "fields.frm2000:txtTax15C"
"frm2000:txtTax15D" = "fields.frm2000:txtTax15D"
"frm2000:txtTax16" = "fields.frm2000:txtTax16"
"frm2000:txtTax17A" = "fields.frm2000:txtTax17A"
"frm2000:txtTax17B" = "fields.frm2000:txtTax17B"
"frm2000:txtTax17C" = "fields.frm2000:txtTax17C"
"frm2000:txtTax17D" = "fields.frm2000:txtTax17D"
"frm2000:txtTax18" = "fields.frm2000:txtTax18"
"frm2000:txtTax19" = "fields.frm2000:txtTax19"
"txtTaxAgentNo" = "fields.txtTaxAgentNo"
"txtDateIssue" = "fields.txtDateIssue"
"txtDateExpiry" = "fields.txtDateExpiry"
"frm2000:txtAgency20" = "fields.frm2000:txtAgency20"
"frm2000:txtNumber20" = "fields.frm2000:txtNumber20"
"frm2000:txtDate20" = "fields.frm2000:txtDate20"
"frm2000:txtAmount20" = "fields.frm2000:txtAmount20"
"frm2000:txtAgency21" = "fields.frm2000:txtAgency21"
"frm2000:txtNumber21" = "fields.frm2000:txtNumber21"
"frm2000:txtDate21" = "fields.frm2000:txtDate21"
"frm2000:txtAmount21" = "fields.frm2000:txtAmount21"
"frm2000:txtAgency22" = "fields.frm2000:txtAgency22"
"frm2000:txtNumber22" = "fields.frm2000:txtNumber22"
"frm2000:txtDate22" = "fields.frm2000:txtDate22"
"frm2000:txtAmount22" = "fields.frm2000:txtAmount22"
"frm2000:txtParticular36" = "fields.frm2000:txtParticular36"
"frm2000:txtAgency23" = "fields.frm2000:txtAgency23"
"frm2000:txtNumber23" = "fields.frm2000:txtNumber23"
"frm2000:txtDate23" = "fields.frm2000:txtDate23"
"frm2000:txtAmount23" = "fields.frm2000:txtAmount23"
"frm2000:txtPg2TIN1" = "fields.frm2000:txtPg2TIN1"
"frm2000:txtPg2TIN2" = "fields.frm2000:txtPg2TIN2"
"frm2000:txtPg2TIN3" = "fields.frm2000:txtPg2TIN3"
"frm2000:txtPg2BranchCode" = "fields.frm2000:txtPg2BranchCode"
"frm2000:txtPg2TaxpayerName" = "fields.frm2000:txtPg2TaxpayerName"
"chkSchedule1Delete0" = "fields.chkSchedule1Delete0"
"drpATCCode0" = "fields.drpATCCode0"
"frm2000:sched1:txtTaxBase0" = "fields.frm2000:sched1:txtTaxBase0"
"frm2000:sched1:txtTaxRate0" = "fields.frm2000:sched1:txtTaxRate0"
"frm2000:sched1:txtTaxDue0" = "fields.frm2000:sched1:txtTaxDue0"
"frm2000:sched1:txtTotalDue1" = "fields.frm2000:sched1:txtTotalDue1"
"frm2000:sched2:txtTotalPayment1" = "fields.frm2000:sched2:txtTotalPayment1"
"chkSchedule3Delete0" = "fields.chkSchedule3Delete0"
"frm2000:sched3:txtPaymentDate0" = "fields.frm2000:sched3:txtPaymentDate0"
"frm2000:sched3:txtReceipt0" = "fields.frm2000:sched3:txtReceipt0"
"frm2000:sched3:txtAmountPaid0" = "fields.frm2000:sched3:txtAmountPaid0"
"chkSchedule3Delete1" = "fields.chkSchedule3Delete1"
"frm2000:sched3:txtPaymentDate1" = "fields.frm2000:sched3:txtPaymentDate1"
"frm2000:sched3:txtReceipt1" = "fields.frm2000:sched3:txtReceipt1"
"frm2000:sched3:txtAmountPaid1" = "fields.frm2000:sched3:txtAmountPaid1"
"chkSchedule3Delete2" = "fields.chkSchedule3Delete2"
"frm2000:sched3:txtPaymentDate2" = "fields.frm2000:sched3:txtPaymentDate2"
"frm2000:sched3:txtReceipt2" = "fields.frm2000:sched3:txtReceipt2"
"frm2000:sched3:txtAmountPaid2" = "fields.frm2000:sched3:txtAmountPaid2"
"frm2000:sched3:txtTotalPayment1" = "fields.frm2000:sched3:txtTotalPayment1"
"frm2000:sched4:txtTotalRemittance1" = "fields.frm2000:sched4:txtTotalRemittance1"
"frm2000:txtCurrentPage" = "fields.frm2000:txtCurrentPage"
"frm2000:txtMaxPage" = "fields.frm2000:txtMaxPage"
"frm2000:modLabel" = "fields.frm2000:modLabel"
"ds106modYes" = "fields.ds106modYes"
"ds106modNo" = "fields.ds106modNo"
"frm2000:numOfDays" = "fields.frm2000:numOfDays"
"ds130modYes" = "fields.ds130modYes"
"ds130modNo" = "fields.ds130modNo"
"frm2000:numOfMonths" = "fields.frm2000:numOfMonths"
"ds131modYes" = "fields.ds131modYes"
"ds131modNo" = "fields.ds131modNo"
"frm2000:numOfMonths131" = "fields.frm2000:numOfMonths131"
"ds132modYes" = "fields.ds132modYes"
"ds132modNo" = "fields.ds132modNo"
"frm2000:numOfMonths132" = "fields.frm2000:numOfMonths132"
"frm2000:txtLineBus" = "fields.frm2000:txtLineBus"
