"txtMonthDate" = "fields.txtMonthDate"
"AmendedRtn_1" = "fields.AmendedRtn_1"
"AmendedRtn_2" = "fields.AmendedRtn_2"
"txtSheets" = "fields.txtSheets"
"txtTIN1" = "fields.txtTIN1"
"txtTIN2" = "fields.txtTIN2"
"txtTIN3" = "fields.txtTIN3"
"txtBranchCode" = "fields.txtBranchCode"
"txtRDOCode" = "fields.txtRDOCode"
"txtTaxpayerName" = "fields.txtTaxpayerName"
"txtAddress" = "fields.txtAddress"
"txtZipCode" = "fields.txtZipCode"
"txtTelNum" = "fields.txtTelNum"
"txtEmail" = "fields.txtEmail"
"optCreditor" = "fields.optCreditor"
"optDebtor" = "fields.optDebtor"
"optOtherPartyNone" = "fields.optOtherPartyNone"
"txtOtherPartyName" = "fields.txtOtherPartyName"
"txtOtherPartyTin" = "fields.txtOtherPartyTin"
"optEdstSystem" = "fields.optEdstSystem"
"optConstructiveAffixture" = "fields.optConstructiveAffixture"
"optLooseStamps" = "fields.optLooseStamps"
"txtTax14" = "fields.txtTax14"
"txtTax15A" = "fields.txtTax15A"
"txtTax15B" = "fields.txtTax15B"
"txtTax15C" = "fields.txtTax15C"
"txtTax15D" = "fields.txtTax15D"
"txtTax16" = "fields.txtTax16"
"txtTax17A" = "fields.txtTax17A"
"txtTax17B" = "fields.txtTax17B"
"txtTax17C" = "fields.txtTax17C"
"txtTax17D" = "fields.txtTax17D"
"txtTax18" = "fields.txtTax18"
"txtTax19" = "fields.txtTax19"
"txtAmount20" = "fields.txtAmount20"
"txtAmount21" = "fields.txtAmount21"
"txtAmount22" = "fields.txtAmount22"
"txtParticular23" = "fields.txtParticular23"
"txtAmount23" = "fields.txtAmount23"
"sched1:txtATC1" = "fields.sched1_txtATC1"
"sched1:txtTaxBase1" = "fields.sched1_txtTaxBase1"
"sched1:txtTaxRate1" = "fields.sched1_txtTaxRate1"
"sched1:txtTaxDue1" = "fields.sched1_txtTaxDue1"
"sched1:txtTotalTaxDue" = "fields.sched1_txtTotalTaxDue"
"sched2:txtTotalPayments" = "fields.sched2_txtTotalPayments"
"sched3:txtTotalAdvancePayments" = "fields.sched3_txtTotalAdvancePayments"
"sched4:txtTotalRemittance" = "fields.sched4_txtTotalRemittance"
